name: babyai1
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.6
    - pytorch=1.4
    - torchvision
    - pyqt
    - numpy
    - blosc
    - pip
    - pip:
        - gym
        - scikit-build
